### ISSUE TITLE
Implement database upgrades

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#18]
Currently database have to be deleted when new version is released. Database upgrades must be implemented to update tables and records to new versions. This could be helpful: https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

**Comment by KrystianKempski** [comment]
pending tests in future

**Comment by KrystianKempski** [comment]
tests succeded
