### ISSUE TITLE
Can't go back to campagins available for Game Master

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#19]
Steps to reproduce:
1. Create a character on GM account.
2. Go to campaign.
3. Select available campaigns for character:
![image](https://github.com/user-attachments/assets/8a569127-8240-4a18-8b02-e37091a368cf)
4. Can't go back to GM:
![image](https://github.com/user-attachments/assets/e36ed0fa-9029-4983-9055-868f834cbca8)

**Comment by KrystianKempski** [comment]
problem no longer exists, as selection was moved to login display
