### ISSUE TITLE
Equipment table scrolls the whole page

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#3]
In character creation screen when adding existing items to equipment and scrolling, when table with equipment ends it starts to scroll the page underneath. This could be resolved by adding `overscroll-behavior-y: contain;` to the table.

Steps to reproduce:
1. Go to Character list
2. Add new character
3. Go to Equipment table and click add existing
4. Start scrolling till you get to the bottom.

**Comment by KrystianKempski** [comment]
I did added overscroll-behavior-y: contain; to tables, and behaviour didnt change. I will try again

**Comment by drikqlis** [comment]
I works for the equipment table itself correctly now, but this is about popup table that opens when you click "Add existing item".
