### ISSUE TITLE
Add edit and remove option for purse records

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#47]
Currently there is no option to remove or edit purse records. This can cause issues if there is a mistake in the record.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added edit and delete buttons to the WealthRecordsDialog. Implemented methods to handle editing and deleting of wealth records. Updated the UI to reflect these changes.

You can review changes in this commit: https://github.com/lkilu6456546/KrystianKempski-DagoniteEmpire-47/commit/7f2bce2cf032b7bf6ec9dbb410f56b824c47fe8d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
