### ISSUE TITLE
Can't add images in campagin

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#6]
When trying to paste images to campaign it adds text with image name instead:
![image](https://github.com/user-attachments/assets/f01708ed-21c1-410f-a056-9a100e69ed19)
When trying to add image using provided button Insert is greyed out and can't be pressed:
![image](https://github.com/user-attachments/assets/556f8112-2383-4b26-b808-847c51e92676)
When dragging and dropping image it saves but is gone after page refresh:
![image](https://github.com/user-attachments/assets/aebcf20e-c400-412e-9074-796703895e1b)

**Comment by KrystianKempski** [comment]
should work now
